### ISSUE TITLE
Ooops Class constructor PuppetPadplus cannot be invoked without 'new'

### ISSUE THREAD

**Issue by artxia** [UnsignedInt8/leavexchat-bot#13]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ✅] question about how to use this project

* **Summary**
你好，我在安装后，通过tg登录微信，时出现如下错误提示。
环境：
ubuntu18  
node 12/10 都试过
pad_token 有 ，我有一个试用

```
03:08:40 INFO Bot is running
03:08:40 INFO Recovering 0 sessions...
03:08:48 ERROR Ooops Class constructor PuppetPadplus cannot be invoked without 'new'
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by UnsignedInt8** [comment]
现在最新的版本还有吗

**Comment by artxia** [comment]
> 现在最新的版本还有吗

😂 但是申请的pad_token早已过期。。貌似Wechaty已经放弃pad了
介于微信web登录一直在缩小适用范围，不知道您是否有考虑换成github上其他可用的微信api

**Comment by UnsignedInt8** [comment]
其它三方做的API，我都没去了解过😂

web只能说是够用，而且这个bot我也大概用了有2年了，觉得还是蛮舒服的。至少在全面停止web版本之前，我会一直用这个bot 😄

**Comment by artxia** [comment]
> 其它三方做的API，我都没去了解过😂
> 
> web只能说是够用，而且这个bot我也大概用了有2年了，觉得还是蛮舒服的。至少在全面停止web版本之前，我会一直用这个bot 😄

你是幸运的，能使用web微信。
我也是想逃离微信，从EFB一直在找你这个项目，都因为web禁止了我登录而失败。可能很多想要逃离微信的人都被这一步限制了。。
后来发现你的项目里可以使用pad的token，我又燃起了希望，没想到还是没成功哈哈哈。。。
总之，这是一个非常棒的项目～
