### ISSUE TITLE
web 登录可以通过 UOS 的自定义标头绕过登录限制，还请升级一下依赖

### ISSUE THREAD

**Issue by artxia** [UnsignedInt8/leavexchat-bot#20]
作者你好，最近网上出现UOS的微信客户端，实际上就是原web客户端自定义了标头。
这样就可以绕开微信限制，而实现登录。

wechaty也已经测试上传了最新文件，还请更新一下版本
参考：
https://github.com/wechaty/wechaty-puppet-wechat/issues/127

**Comment by UnsignedInt8** [comment]
谢谢告知，我看看。能绕开微信登陆限制就太棒了

**Comment by UnsignedInt8** [comment]
已经全部升级到最新版 wechaty 了，等待UOS支持

**Comment by artxia** [comment]
wechaty-puppet-wechat 0.28.1 https://github.com/wechaty/wechaty-puppet-wechat/commit/6975f402960f0af34f8a39341444228a31a97594
wechaty 0.60.3 https://github.com/wechaty/wechaty/commit/9ea648d86386f8047d68a982e2c5e77cb6326d93

wechaty 已经完成重要更新，我试了下 leavexchat-bot 改了版本号后已经可以成功登录

**Comment by UnsignedInt8** [comment]
> wechaty-puppet-wechat 0.28.1 [wechaty/wechaty-puppet-wechat@6975f40](https://github.com/wechaty/wechaty-puppet-wechat/commit/6975f402960f0af34f8a39341444228a31a97594)
> wechaty 0.60.3 [wechaty/wechaty@9ea648d](https://github.com/wechaty/wechaty/commit/9ea648d86386f8047d68a982e2c5e77cb6326d93)
> 
> wechaty 已经完成重要更新，我试了下 leavexchat-bot 改了版本号后已经可以成功登录

Great!

**Comment by UnsignedInt8** [comment]
已全部更新，推荐用yarn装dependencies

**Comment by artxia** [comment]
> 已全部更新，推荐用yarn装dependencies

我自己构建了[docker](https://github.com/artxia/leavexchat-bot-docker)来运行也满稳的

不过有个小疑惑，不知道是不是我使用方法不对：
每个消息过来后，单独回复和查看都只能在这个bot里面进行。那么当有大量工作微信和群微信的时候，所有信息都混在这个bot里面，聊天记录的查找和上下文关联都蛮困难的。。我试过将bot拉入一个新群，然后锁定bot联系人为某人，以这样的方式来建立一个个独立的聊天框。。貌似这种情况无法锁定？

**Comment by UnsignedInt8** [comment]
> > 已全部更新，推荐用yarn装dependencies
> 
> 我自己构建了[docker](https://github.com/artxia/leavexchat-bot-docker)来运行也满稳的
> 
> 不过有个小疑惑，不知道是不是我使用方法不对：
> 每个消息过来后，单独回复和查看都只能在这个bot里面进行。那么当有大量工作微信和群微信的时候，所有信息都混在这个bot里面，聊天记录的查找和上下文关联都蛮困难的。。我试过将bot拉入一个新群，然后锁定bot联系人为某人，以这样的方式来建立一个个独立的聊天框。。貌似这种情况无法锁定？

这种用法我确实没有考虑过，因为设计的时候，bot只有一个当前联系人，所以每次回复消息的时候，要么就是引用某条消息再回复，要么就是锁定。如果是有大量的消息，的确是一件头疼的事

我觉得这个bot还是偏向于日常生活上的使用，不太适用于工作的情况
